[env]
TERM = "xterm-256color"

[font]
size = 16

  [font.normal]
  family = "Hack Nerd Font Mono"
  style = "Regular"

  [font.bold]
  family = "Hack Nerd Font Mono"
  style = "Bold"

  [font.italic]
  family = "Hack Nerd Font Mono"
  style = "Italic"

  [font.bold_italic]
  family = "Hack Nerd Font Mono"
  style = "Bold Italic"

[window]
option_as_alt = "Both"
dynamic_padding = false
decorations = "buttonless"
startup_mode = "Windowed"
opacity = 0.9

  [window.padding]
  x = 12
  y = 12

[colors.primary]
background = "#1d2021"
foreground = "#d4be98"

[colors.cursor]
text = "#c9c7cd"
cursor = "#757581"

[colors.normal]
black = "#32302f"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#32302f"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

