[dependencies]
cmake = { version = "latest" }
fzf = { version = "latest" }
git = { version = "latest" }
hyprland = { steps = [ "git clone --recursive https://github.com/hyprwm/Hyprland", "cd Hyprland", "make all && sudo make install" ] }
nvim = { script = "nvim.sh" }
ripgrep = { version = "14.1.1-1" }
tmux = { post_install_script = "tmux.sh" }
zig = { version = "0.13.0" }
zsh = { post_install_steps = [ "chsh -s $(which zsh)" ] }
